### ISSUE TITLE
join-misskeyページおよびこのリポジトリへの提案事項

### ISSUE THREAD

**Issue by 4ioskd** [joinmisskey/new-joinmisskey#14]
現在サイトおよびこのリポジトリを作成中とのことで、以下提案をつらつらと。長いので、必要と思われるものを自由にcheery pickなさって下さい。開発で忙しければ、このissueへの対応自体の後回しは問題ありません。

join-misskey,page
・言語切り替えのリンク欄は、サイト最上部右側の方がユーザーには優しそう
・ページ最下部右下の「 Ⓒ2021 Let's start Misskey」は、「Copyright Ⓒ2021 Let's start Misskey」とした方が良さそう
・Misskeyプロジェクトおよびそのロゴのクレジット表示
・プライバシーポリシーの作成（作成ツールがあったはず）
・細かいですが、instanceページの言語表記は小文字より大文字が良いかと（例：ja→JA)
・お問い合わせ欄の作成
・各アカウントの表記は以下の様にした方がすっきりするかもしれない

Misskey(の欄）
misskey-dev/misskey
Patreon
Crowdin
@ syuilo@misskey.io（Main Developer of Misskey)

Let's start Misskey（の欄）
joinmisskey/new-joinmisskey
joinmisskey/api
GitLocalize
@ joinmisskey@misskey.io(Official Account of this site)

リポジトリ
・コントリビューションガイド、翻訳ガイドの作成
・READMEの内容が充実してくれば、翻訳コントリビューションします
・ライセンス表記
・README内のクレジット表記

全体の話
・呼称を「Let's start Misskey」で全て統一する？？

**Comment by tamaina** [comment]
よくわからんからIssue分けてほしい

**Comment by 4ioskd** [comment]
細かくなるけど、それでもいいなら。

**Comment by tamaina** [comment]
何個でも立ててどうぞ（やるかどうかは別として）
