### ISSUE TITLE
Instances with version modifiers downranked 

### ISSUE THREAD

**Issue by ThatOneCalculator** [joinmisskey/new-joinmisskey#22]
Technically this is an issue with https://github.com/joinmisskey/api but that repo doesn't accept issues.

My instance runs `12.112.0-t1c.b8.2` and is placed at the bottom of the list instead of the top because of the `-t1c.b8.2` part. Sorting by version should not include anything after a `-`.

**Comment by tamaina** [comment]
misskey-dev/misskeyに12.112.0というバージョンが存在しないのが原因なのですが、私は解決策が思い浮かびません。

**Comment by ThatOneCalculator** [comment]
Perhaps instead of existing tags in Misskey, just take each tag and use [semver-sort](https://www.npmjs.com/package/semver-sort) to sort it from highest to lowest?
