### ISSUE TITLE
`thatonecalculator/calckey` repository source

### ISSUE THREAD

**Issue by ThatOneCalculator** [joinmisskey/new-joinmisskey#23]
https://stop.voring.me now runs on https://codeberg.org/thatonecalculator/calckey, and some other instances might be migrating too :)

**Comment by tamaina** [comment]
needs https://github.com/joinmisskey/new-joinmisskey/issues/25

**Comment by tamaina** [comment]
needs https://github.com/joinmisskey/new-joinmisskey/issues/25

**Comment by tamaina** [comment]
done

**Comment by ThatOneCalculator** [comment]
It shows now, but still reports the repository as `misskey-dev/misskey`, not `thatonecalculator/calckey`

![Screenshot_20221130-090651.png](https://user-images.githubusercontent.com/44733677/204862431-5be03be2-d34c-4c04-9d0d-cbb5f337ff65.png)

**Comment by tamaina** [comment]
なんでええ

**Comment by tamaina** [comment]
いや、とりあえずgiteaの処理できるようになったから対応するだろと思ってたのがいけないんだけど

**Comment by tamaina** [comment]
![image](https://user-images.githubusercontent.com/7973572/204879393-03ed1fc2-69af-4252-bf8c-0bcfde7c79fd.png)

**Comment by tamaina** [comment]
@ThatOneCalculator が変なバージョンの付け方してるせいだわ

**Comment by ThatOneCalculator** [comment]
@tamaina That versioning scheme is temporary, next update or so it's going to be `v13.0.0`

**Comment by ThatOneCalculator** [comment]
@tamaina yea, with the new v13 it's resolved :) 

![image](https://user-images.githubusercontent.com/44733677/208218525-d391ae9b-2c27-4cde-9ff6-1c0a2876dd56.png)
