### ISSUE TITLE
Foundkeyをフォークに追加

### ISSUE THREAD

**Issue by futchitwo** [joinmisskey/new-joinmisskey#24]
https://akkoma.dev/FoundKeyGang/FoundKey
Foundkeyは主に以前Pleromaを利用していた海外インスタンスが利用しています。

注意点として、バージョンに修飾子をつけているのではなく、ソフトウェア名をMisskey から書き換えているため、https://github.com/joinmisskey/api にも独自の処理が必要です。

上記の理由によって、Foundkeyインスタンスは現在JoinMisskeyのリストには掲載されておらず、Misskeyの総ユーザー数等のカウントには含まれていません。

**Comment by tamaina** [comment]
needs https://github.com/joinmisskey/new-joinmisskey/issues/25

**Comment by tamaina** [comment]
done
