### ISSUE TITLE
Support languages where the digit separator is not a comma

### ISSUE THREAD

**Issue by tamaina** [joinmisskey/new-joinmisskey#32]

**Comment by tassoman** [comment]
Does it fits? 
https://thewebdev.info/2020/08/03/vue-i18n%E2%80%8A-%E2%80%8Aformatting-text-and-numbers/

**Comment by tamaina** [comment]
Hmm.. it used http://numeraljs.com/ and this should have the solution.

**Comment by tamaina** [comment]
I find browser native api: https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

**Comment by tamaina** [comment]
Implemented

**Comment by tassoman** [comment]
Thank you! It's a flawless solution
最高、ありがとうございました
メッリクリスマス :christmas_tree:
