### ISSUE TITLE
some instances are wrongly marked as dead

### ISSUE THREAD

**Issue by tassoman** [joinmisskey/new-joinmisskey#40]
Misskey Social went into [deads.txt](https://instanceapp.misskey.page/deads.txt) API file by mistake.  
[No italian server is listed](https://join.misskey.page/it-IT/instances).  
Please remove from api `deads.txt` any PR can't be issued, must be done by hands.

**Comment by tamaina** [comment]
It seems that requests from the joinmisskey API are not getting through, bot protection or something else may be at fault.
Allowing the following UserAgent may solve the problem:
`JoinMisskey/0.1.0; +https://join.misskey.page/instances`

**Comment by tassoman** [comment]
I can't `grep -i joinmisskey` bot inside reverse proxy nginx access log.  
Which server's endpoint is asked?  
We are not filtering bots as far I know
[robots.txt](https://misskey.social/robots.txt) is allowing everything

**Comment by tassoman** [comment]
misskey.de also was blacklisted as dead, but we're both alive and competing as beautiful Misskey European servers  🥺

**Comment by tamaina** [comment]
Listed in deads.txt doesn't mean blacklisted. It means the bot couldn't access to the servers.

**Comment by tamaina** [comment]
> Which server's endpoint is asked?

/.well-known/nodeinfo

**Comment by tassoman** [comment]
I was able to curl nodeinfo paths (well-known and 2.0) but no evidence of joinmisskey client.  
While I was reading logs, got istantly a ping:

```logs
58.96.yyy.xxx - - [24/Jul/2023:23:47:48 +0000] "GET /.well-known/nodeinfo HTTP/1.1" 200 114 "-" "mint/1.5.1"
58.96.yyy.xxx - - [24/Jul/2023:23:47:48 +0000] "GET /nodeinfo/2.0 HTTP/1.1" 200 1300 "-" "Akkoma 3.9.3-28-g9d7c877d; https://fedi.worf.win <me@worf.win>"
```
