### ISSUE TITLE
Beta版サーバーは表示しないか優先順位を下げる

### ISSUE THREAD

**Issue by tkmrgit** [joinmisskey/new-joinmisskey#45]
Beta版がトップに表示される状態が続いている。Beta版を使うこと自体は別に良いと思うが、サーバー一覧のトップに表示されるのは安定性が保証されていない(※Misskeyのstableが安定しているとは限らないのだが) のと、あまり望ましくない動作に思えるのでBeta版稼働サーバーをデフォルトで表示させないか、優先順位を下げてもらいたい

**表示関連Issue**
#44 

**Beta版について同様のIssue**
#42

**Comment by tamaina** [comment]
Duplicate of #42
